POST http://localhost:8081/mapi/jaipur/restaurant  HTTP/1.1
content-type: application/json

{
    "restaurant_id": 10001,
    "restauramt_name": "RJ 14",
    "restaurant_url": "",
    "restaurant_mapped_id": {
        "restaurant_zomato_id": 103172,
        "restaurant_swiggy_id": 46961,
        "restaurant_dineout_id": 50802,
        "restaurant_eazydiner_id": 645171
    },
    "restaurant_mapped_name": {
        "restaurant_zomato_id": "RJ 14",
        "restaurant_swiggy_id": "RJ14",
        "restaurant_dineout_id": "RJ 14",
        "restaurant_eazydiner_id": "RJ 14"
    },
    "restaurant_mapped_url": {
        "restaurant_zomato_url": "https://www.zomato.com/jaipur/rj-14-ajmer-highway/order",
        "restaurant_swiggy_url": "https://www.swiggy.com/restaurants/rj14-dcm-road-brijlalpura-jaipur-46961?sld=false",
        "restaurant_dineout_url": "https://www.dineout.co.in/jaipur/rj-14-ajmer-road-west-jaipur-50802",
        "restaurant_eazydiner_url": "https://www.eazydiner.com/jaipur/rj-14-ajmer-highway-jaipur-645171"
    },
    "dining_rating": {
        "dining_zomato_rating": {"reviewCount": 3947, "rating": 4.4},
        "dining_dineout_rating":  {"reviewCount": 694, "rating": 4.2},
        "dining_eazydiner_rating":  {"reviewCount": 362, "rating": 4.4}
    },
    "delivery_rating": {
        "delivery_zomato_rating":  {"reviewCount": 8819, "rating": 4.1},
        "delivery_swiggy_rating":  {"reviewCount": 1000, "rating": 4.1}
    },
     "restaurant_address": {
        "address": "132, 133, 151, Ajmera Garden, Main DCM Road, Opposite IndusInd Bank, Ajmer Highway, Jaipur",
        "locality_code": 4,
        "locality_name": "Ajmer Highway",
        "locality_url": "/jaipur/AjmerHighway",
        "city_name": "Jaipur",
        "city_id": 1,
        "city_url": "/jaipur/restaurants"
    },
    "restaurant_scrap_url": {
        "restaurant_zomato_scrap_url": "https://www.zomato.com/webroutes/getPage?page_url=/jaipur/rj-14-ajmer-highway&location=&isMobile=0",
        "restaurant_swiggy_scrap_url": "https://www.swiggy.com/dapi/menu/v4/full?lat=26.9124336&lng=75.7872709&menuId=46961",
        "restaurant_dineout_scrap_url": "https://www.dineout.co.in/jaipur/rj-14-ajmer-road-west-jaipur-50802",
        "restaurant_eazydiner_scrap_url": "https://force.eazydiner.com/5.1/restaurants/jaipur/rj-14-ajmer-highway-jaipur-645171"
    },
    "directions": {
        "google_maps_url": "",
        "latitude": 26.8952975644,
        "longitude": 75.7506003231
    },
    "contact_details": {
        "phone": ["+919649488811", "+91 9887125555", "+919649488855"]
    },
    "cuisines": [
    {
        "cuisine_name": "North Indian",
        "cuisine_url": "/jaipur/NorthIndian"
    },
    {
        "cuisine_name": "Desserts",
        "cuisine_url": "/jaipur/Desserts"
    },
    {
        "cuisine_name": "Beverages",
        "cuisine_url": "/jaipur/Beverages"
    }],
    "timings": [{
        "timing": "12noon - 11pm"
        //days: String
    }],
    "images": [
    "https://b.zmtcdn.com/data/pictures/2/103172/0c6e6c8e24098abaec6f67143f447da2.jpg?output-format=webp",
    "https://b.zmtcdn.com/data/pictures/2/103172/65bfde630adf5ba06925ff95260d2051.jpg?output-format=webp",
    "https://b.zmtcdn.com/data/pictures/2/103172/45d5896371b8162e0eb98c5bac2f4032.jpg?output-format=webp",
    "https://b.zmtcdn.com/data/pictures/2/103172/a7e65a96b698eb6e97d6813ec8ee7783.jpg?output-format=webp",
    "https://b.zmtcdn.com/data/pictures/2/103172/56f691c6ce2f13074a7659ef13e24e9f.jpg?output-format=webp"   
    ],
    "index_image": "https://b.zmtcdn.com/data/pictures/2/103172/0c6e6c8e24098abaec6f67143f447da2.jpg?output-format=webp",
    "cost_for_two": 1000,
    "features": ["Home Delivery", "Takeaway Available", "Vegetarian Only", "Free Parking", "alet Parking Available", "Indoor Seating", "Desserts and Bakes", "Live Sports Screening", "Outdoor Seating", "Table reservation required" ],
    "feature_rail": ["Well Sanitized Kitchen", "Daily Temp. Checks"],
    "people_liked": ["Food was Wonderful", "Quality of Food", "Communication", "Affordable", "Desi Food", "Waiting Time"],
    "top_dishes": ["Dahi Papadi Chaat", "Rabri Malpua", "Masala Soda", "Tomato Shorba", "Junglee Roti"," Dahi Kebab"],
    //top_tags: [String],
    "category": "Casual Dining",
    "chain": false,
    "chain_url": "",
    "isNewDineout": false,
    "isNewSwiggy": false,
    "isNewZomato": false,
    "isVeg": true,
    "fssaiNo": 12218026000975,
    "menuType": "Zomato"
}


PUT http://localhost:8081/mapi/jaipur/restaurant/62bd2c8899ede46d7528ba26  HTTP/1.1
content-type: application/json

{
    "zomato_offer": [
    {
        "code": "ZOMPAYTM",
        "title": "₹30 Paytm cashback using Paytm",
        "subtitle": "Valid on total value of items worth ₹159 or more.",
    },
    {
        "code": "SIMPLNEW",
        "title": "Get Flat ₹40 OFF",
        "subtitle": "Valid on orders with items worth ₹159 or more",
    },
    {
        "code": "",
        "title": "Flat 50% OFF",
        "subtitle": "Get flat 50% OFF on all orders.",
    },
    {
        "code": "LAZYPAY75",
        "title": "Get ₹75 LazyPay cashback on your first LazyPay transaction",
        "subtitle": "Valid on total value of items worth ₹159 or more",
    }],
    "swiggy_offer": [
    {
        "code": "USE TRYNEW", 
        "title": "0% OFF UPTO ₹120", 
        "subtitle": "ABOVE ₹129"    
    },
    {
        "code": "USE WELCOME50", 
        "title": "50% OFF + ₹30 CASHBACK", 
        "subtitle": "PAYTM CASHBACK" 
    },
    {
        "code": "USE JUMBO", 
        "title": "30% OFF UPTO ₹150", 
        "subtitle": "ABOVE ₹400"
    }],
    "dineout_offer": [
    {
        "code": "", 
        "title": "Flat 10% Off the Total Bill", 
        "subtitle": "Additional 10% Off when paid with PromoCash"    
    },
    {
        "code": "", 
        "title": "Get Extra Upto 15% Off", 
        "subtitle": "with HDFC Bank Credit card"    
    }],
    "eazydiner_offer": [{
        "code": "", 
        "title": "10% off on food & soft bev.", 
        "subtitle": " Enjoy an Extra 40% off upto Rs. 1000 when you pay via the EazyDiner App"
    }]

}